baseline: 測試baseline
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
title: 測試title
description: 測試description
baseurl: /
canonicalurl: true
date:
  format: j F Y
  timezone: Asia/Hong Kong
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
postprocess:
  enabled: true
